import jsPDF from 'jspdf';

export function generateCertificatePDF(participantName: string, score: number): void {
  const name = participantName.trim() || 'Participant';
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });
  const width = doc.internal.pageSize.getWidth();
  const height = doc.internal.pageSize.getHeight();

  // Background
  doc.setFillColor('#f7f7ff');
  doc.rect(0, 0, width, height, 'F');

  // Border
  doc.setDrawColor('#444');
  doc.setLineWidth(3);
  doc.rect(24, 24, width - 48, height - 48);

  // Title
  doc.setTextColor('#222');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(36);
  doc.text('Certificate of Completion', width / 2, 120, { align: 'center' });

  // Subtitle
  doc.setFontSize(18);
  doc.setFont('helvetica', 'normal');
  doc.text('User Story Improvement Exercise', width / 2, 160, { align: 'center' });

  // Name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.text(name, width / 2, 230, { align: 'center' });

  // Score
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(20);
  doc.text(`Score: ${score} / 100`, width / 2, 270, { align: 'center' });

  const date = new Date().toLocaleDateString();
  doc.setFontSize(14);
  doc.text(`Issued on ${date}`, width / 2, 300, { align: 'center' });

  // Footer
  doc.setFontSize(12);
  doc.text('Generated by User Story Improver', width / 2, height - 60, { align: 'center' });

  doc.save(`certificate_${name.replace(/\s+/g, '_')}.pdf`);
} 